# /home/ide/docker-compose.yml
version: "3"

services:
    proxy:
        image: traefik:latest
        container_name: traefik
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /home/web/.letsencrypt:/letsencrypt
        command:
            - --providers.docker=true
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --certificatesresolvers.cn.acme.tlschallenge=true
            - --certificatesresolvers.cn.acme.email=${ACME_EMAIL}
            - --certificatesresolvers.cn.acme.storage=/letsencrypt/acme.json
        ports:
            - 80:80
            - 443:443

    blog:
        image: ghcr.io/zchoate/blog:main
        container_name: blog
        labels:
            - traefik.enable=true
            - traefik.http.routers.blog.rule=Host(`blog.choate.network`)
            - traefik.http.routers.blog.entrypoints=web
            - traefik.http.routers.blogtls.rule=Host(`blog.choate.network`)
            - traefik.http.routers.blogtls.entrypoints=websecure
            - traefik.http.routers.blogtls.tls.certresolver=cn
            - traefik.http.middlewares.blog-redirect.redirectscheme.scheme=https
            - traefik.http.middlewares.blog-redirect.redirectscheme.permanent=true
            - traefik.http.routers.blog.middlewares=blog-redirect@docker