# /home/ide/docker-compose.yml
version: "3"

services:
    proxy:
        image: traefik:latest
        container_name: traefik
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /home/web/public_web/.letsencrypt:/letsencrypt
            - /home/web/public_web/docker-compose/traefik.yml:/config.yml:ro
        command:
            - --providers.docker=true
            - --providers.file.filename=/config.yml
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --certificatesresolvers.cn.acme.tlschallenge=true
            - --certificatesresolvers.cn.acme.email=${ACME_EMAIL}
            - --certificatesresolvers.cn.acme.storage=/letsencrypt/acme.json
        ports:
            - 80:80
            - 443:443
        labels:
            - traefik.http.middlewares.devblog-auth.users=dev:${DEV_PASSWORD}

    blog:
        image: ghcr.io/zchoate/blog:main
        container_name: blog
        labels:
            - traefik.enable=true
            - traefik.http.routers.blog.rule=Host(`blog.choate.network`)
            - traefik.http.routers.blog.entrypoints=web
            - traefik.http.routers.blogtls.rule=Host(`blog.choate.network`)
            - traefik.http.routers.blogtls.entrypoints=websecure
            - traefik.http.routers.blogtls.tls.certresolver=cn
            - traefik.http.middlewares.blog-redirect.redirectscheme.scheme=https
            - traefik.http.middlewares.blog-redirect.redirectscheme.permanent=true
            - traefik.http.routers.blog.middlewares=blog-redirect@docker
    
    dev_blog:
        image: ghcr.io/zchoate/blog:dev
        container_name: dev_blog
        labels:
            - traefik.enable=true
            - traefik.http.routers.devblog.rule=Host(`dev.blog.choate.network`)
            - traefik.http.routers.devblog.entrypoints=web
            - traefik.http.routers.devblogtls.rule=Host(`dev.blog.choate.network`)
            - traefik.http.routers.devblogtls.entrypoints=websecure
            - traefik.http.routers.devblogtls.tls.certresolver=cn
            - traefik.http.middlewares.devblog-redirect.redirectscheme.scheme=https
            - traefik.http.middlewares.devblog-redirect.redirectscheme.permanent=true
            - traefik.http.routers.devblog.middlewares=devblog-redirect@docker
            - traefik.http.routers.devblogtls.middlewares=devblog-auth@docker